### ISSUE TITLE
Allow a customized 'default' status/presence for a proxy

### ISSUE THREAD

**Issue by DigitalStarSys** [ashen-dawn/Seance#2]
**Current behavior:** All bots, upon a boot or a reboot, default to either `sync` or `online`, and any custom status they had set is wiped.

**Proposed behavior:** A config setting for setting a bot's default presence and status on startup for the bot. This would be especially nice to be easily configurable via systemd unit. This is useful for systems with large amounts of proxies, to prevent needing to manually run high amounts of `!presence` commands every time there's a reboot or network disconnection.

**Comment by ashen-dawn** [comment]
implemented in 6f98829002ebbac0e47a4771b36181596bf9a23b
